import React from "react"
import Head from "next/head"
import Image from "next/image"
import SideBar from "../sidebar"
import CartView from "../cart"

const Layout = ({ children }) => {
  return (
    <div className="w-screen h-screen bg-grey-90">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-0 p-0 flex">
        <div className="h-screen">
          <SideBar />
        </div>
        <div className="grid grid-cols-3 w-full gap-x-3xlarge mt-base mr-base">
          <div className="col-span-2">{children}</div>
          <div className="h-screen">
            <CartView />
          </div>
        </div>
      </main>
      <footer>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Layout
